force-app/main/default/objects/Property_SalesAI_History__c/Property_SalesAI_History__c.object-meta.xml
<CustomObject>
    <label>Property Sales.AI History</label>
    <nameField>
        <label>Property Sales.AI History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties Sales.AI History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_SalesAI_History__c/fields/Finish_Time__c.field-meta.xml
<CustomField>
    <fullName>Finish_Time__c</fullName>
    <label>Finish Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_History__c/fields/Lead_Errors__c.field-meta.xml
<CustomField>
    <fullName>Lead_Errors__c</fullName>
    <label>Lead Errors</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_History__c/fields/Matched_Leads__c.field-meta.xml
<CustomField>
    <fullName>Matched_Leads__c</fullName>
    <label>Matched Leads</label>
    <summaryFilterItems>
        <field>Property_SalesAI_Match__c.Type__c</field>
        <operation>equals</operation>
        <value>Lead Match</value>
    </summaryFilterItems>
    <summaryForeignKey>Property_SalesAI_Match__c.Property_SalesAI_History__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_History__c/fields/Matched_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Matched_Opportunities__c</fullName>
    <label>Matched Opportunities</label>
    <summaryFilterItems>
        <field>Property_SalesAI_Match__c.Type__c</field>
        <operation>equals</operation>
        <value>Opportunity Match</value>
    </summaryFilterItems>
    <summaryForeignKey>Property_SalesAI_Match__c.Property_SalesAI_History__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_History__c/fields/Opportunity_Errors__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Errors__c</fullName>
    <label>Opportunity Errors</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Finished Successfully</fullName>
            </value>
            <value>
                <fullName>Finished With Errors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Match__c/Property_SalesAI_Match__c.object-meta.xml
<CustomObject>
    <label>Property Sales AI Match</label>
    <nameField>
        <displayFormat>AIMatch-{000000}</displayFormat>
        <label>Property Sales Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Sales AI Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_SalesAI_Match__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Properties_Sales_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Match__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Properties_Sales_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Match__c/fields/Property_SalesAI_History__c.field-meta.xml
<CustomField>
    <fullName>Property_SalesAI_History__c</fullName>
    <label>Property Sales AI History</label>
    <referenceTo>Property_SalesAI_History__c</referenceTo>
    <relationshipLabel>Property Sales AI Matches (Property Sales AI History)</relationshipLabel>
    <relationshipName>Property_Sales_AI_Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Match__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/Property_SalesAI_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Property Sales.AI Settings</label>
</CustomObject>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/AutomaticUpdate__c.field-meta.xml
<CustomField>
    <fullName>AutomaticUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AutomaticUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/IsSetupComplete__c.field-meta.xml
<CustomField>
    <fullName>IsSetupComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A boolean that is set to true only when the required fields above are populated by the UX</description>
    <label>IsSetupComplete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Lead_Address_City__c</fullName>
    <label>Lead Address City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_Address_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Lead_Address_PostalCode__c</fullName>
    <description>What field to use the postalcode to match against</description>
    <label>Lead Address PostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Lead_Address_State__c</fullName>
    <description>What field to use to retrieve the state to match against</description>
    <label>Lead Address State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_Address_Street__c.field-meta.xml
<CustomField>
    <fullName>Lead_Address_Street__c</fullName>
    <description>What field to use to retrieve the street address to match against</description>
    <label>Lead Address Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_History_Duration__c.field-meta.xml
<CustomField>
    <fullName>Lead_History_Duration__c</fullName>
    <description>To define the scope of Leads to query, this number is the # of days, in the past, we want to query the LastModifiedDate and/or CreatedDate</description>
    <label>Lead History Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Lead_Record_Types__c</fullName>
    <description>A comma separated list of 1 or more Lead Record Types</description>
    <label>Lead Record Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_Status_2__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status_2__c</fullName>
    <label>Lead Status 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <description>To define the scope of Leads to query, this is the 1 or more lead status to include. A comma separated list of Lead.Status picklist values</description>
    <label>Lead Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Matched_Lead_Reason__c.field-meta.xml
<CustomField>
    <fullName>Matched_Lead_Reason__c</fullName>
    <description>When a Lead match is found, what &quot;lead reason&quot; to populate</description>
    <label>Matched Lead Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Matched_Lead_Reason_Field__c.field-meta.xml
<CustomField>
    <fullName>Matched_Lead_Reason_Field__c</fullName>
    <description>When a Lead match is found, what Lead field to also update the Reason</description>
    <label>Matched Lead Reason Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Matched_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Matched_Lead_Status__c</fullName>
    <description>When a Lead match is found, what is the lead.status to update</description>
    <label>Matched Lead Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Matched_Opportunity_Reason__c.field-meta.xml
<CustomField>
    <fullName>Matched_Opportunity_Reason__c</fullName>
    <description>When an Opportunity match is found, what is the lost reason to populate</description>
    <label>Matched Opportunity Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Matched_Opportunity_Reason_Field__c.field-meta.xml
<CustomField>
    <fullName>Matched_Opportunity_Reason_Field__c</fullName>
    <description>When an Opportunity match is found, what is the Opportunity field to update the lost reason</description>
    <label>Matched Opportunity Reason Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Matched_Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Matched_Opportunity_Stage__c</fullName>
    <description>When an Opportunity match is found, what is the opportunity.stagename value to update</description>
    <label>Matched Opportunity Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Matching_Day__c.field-meta.xml
<CustomField>
    <fullName>Matching_Day__c</fullName>
    <description>Day of the week that the matching logic will run</description>
    <label>Matching Day</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Address_City__c</fullName>
    <description>What field to use to retrieve the city to match against</description>
    <label>Opportunity Address City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_Address_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Address_PostalCode__c</fullName>
    <description>What field to use the postalcode to match against</description>
    <label>Opportunity Address PostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Address_State__c</fullName>
    <description>What field to use to retrieve the state to match against</description>
    <label>Opportunity Address State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_Address_Street__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Address_Street__c</fullName>
    <description>What field to use to retrieve the street address to match against</description>
    <label>Opportunity Address Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_History_Duration__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_History_Duration__c</fullName>
    <description>To define the scope of Opportunity to query, this number is the # of days, in the past, we want to query the LastModifiedDate and/or CreatedDate</description>
    <label>Opportunity History Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record_Types__c</fullName>
    <description>A comma separated list of 1 or more Opportunity Record Types</description>
    <label>Opportunity Record Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_Stage_2__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage_2__c</fullName>
    <label>Opportunity Stage 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <description>To define the scope of Opportunities to query, this is the 1 or more Opportunity Stage(s) to include. A comma separated list of Opportunity.StageName picklist values</description>
    <label>Opportunity Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Property_Sales_History_Duration__c.field-meta.xml
<CustomField>
    <fullName>Property_Sales_History_Duration__c</fullName>
    <description>To define the scope of Property Sales.AI records to include in the matching logic, this number is the # of days in the past (based on the property sold date) we want to query.</description>
    <label>Property Sales History Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ConfigurationController.cls
public with sharing class ConfigurationController {
    
    @AuraEnabled(cacheable=true)
    public static List<RecordType> getRecordTypes(String objectApiName) {
        if (Schema.SObjectType.RecordType.isAccessible()) {
            List<RecordType> rts = [SELECT Id, Name FROM RecordType WHERE SObjectType = :objectApiName AND IsActive = true WITH SECURITY_ENFORCED];
           
            rts = (List<RecordType>) Security.stripInaccessible(AccessType.READABLE, rts).getRecords();
            return rts;
        } else  {
            throw new AuraHandledException('No access to RecordTypes');
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<PickListWrapper> getStatuses(String objectApiName) {
        List<PicklistEntry> statuses = new List<PicklistEntry>();

        if (objectApiName == 'Lead') {
            statuses = Lead.Status.getDescribe().getPicklistValues();
        } else if (objectApiName == 'Opportunity') {
            statuses = Opportunity.StageName.getDescribe().getPicklistValues();
        }
        return getWrapperList(statuses);
    }

    @AuraEnabled
    public static List<PickListWrapper> getPicklistValuesForField(String objectApiName, String fieldApiName) {
        List<PicklistEntry> picklistValues = new List<PicklistEntry>();
        try {
            Schema.SObjectType sObjectType = Schema.getGlobalDescribe().get(objectApiName);
            Schema.DescribeSObjectResult describeSObjectResult = sObjectType.getDescribe();
            Schema.SObjectField field = describeSObjectResult.fields.getMap().get(fieldApiName);
            picklistValues = field.getDescribe().getPicklistValues();
            return getWrapperList(picklistValues);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getExecutionHistory() {
        // Ensure the user has read access to Property_SalesAI_History__c
        if (!Schema.sObjectType.Property_SalesAI_History__c.isAccessible()) {
            throw new AuraHandledException('You do not have access to Property Sales AI history records.');
        }
        
        try {
            // Query the most recent Property_SalesAI_History__c record based on Finish_Time__c
            List<Property_SalesAI_History__c> histories = [
                SELECT Id, OwnerId, Name, Finish_Time__c, Matched_Leads__c, Matched_Opportunities__c, Status__c,
                Lead_Errors__c, Opportunity_Errors__c
                FROM Property_SalesAI_History__c
                WHERE IsDeleted = false
                WITH SECURITY_ENFORCED
                ORDER BY CreatedDate DESC
                LIMIT 1
            ];
            
            Map<String, Object> result = new Map<String, Object>();
            if (histories.size() > 0) {
                result.put('Id', histories[0].Id);
                result.put('Status__c', histories[0].Status__c);
                result.put('Finish_Time__c', histories[0].Finish_Time__c);
                result.put('Matched_Leads__c', histories[0].Matched_Leads__c);
                result.put('Matched_Opportunities__c', histories[0].Matched_Opportunities__c);
                result.put('Lead_Errors__c', histories[0].Lead_Errors__c);
                result.put('Opportunity_Errors__c', histories[0].Opportunity_Errors__c);
                result.put('sObjectAPIName', histories[0].getSObjectType().getDescribe().getName());
                for (ChildRelationship cr : histories[0].getSObjectType().getDescribe().getChildRelationships()) {
                    if(cr.getRelationshipName() != null && cr.getRelationshipName().contains('Properties_Sales_Matches__r')) {
                        result.put('ChildRelationshipName', cr.getRelationshipName());
                    }
                }
            }
            return result;
        } catch (Exception e) {
            // Log the error and handle it gracefully
            System.debug('Error fetching Property_SalesAI_History__c: ' + e.getMessage());
            throw new AuraHandledException('Unable to retrieve Property Sales AI history');
        }
    }

    public static List<PickListWrapper> getWrapperList(List<PicklistEntry> statuses) {
        List<PickListWrapper> result = new List<PickListWrapper>();
        for (PicklistEntry status : statuses) {
            result.add(new PickListWrapper(status.label, status.value));
        }
        return result;
    }

    @AuraEnabled
    public static Map<String, Object> getCustomSettingValues() {
        Map<String, Object> result = new Map<String, Object>();

        // Retrieve the custom setting values (Assuming it's a hierarchy custom setting)
        Property_SalesAI_Settings__c settings = Property_SalesAI_Settings__c.getOrgDefaults();
        
        // Lead custom setting values
        result.put('Lead_Address_PostalCode', settings.Lead_Address_PostalCode__c);
        result.put('Lead_Address_State', settings.Lead_Address_State__c);
        result.put('Lead_Address_Street', settings.Lead_Address_Street__c);
        result.put('Lead_Address_City', settings.Lead_Address_City__c);
        result.put('Lead_Record_Types', settings.Lead_Record_Types__c);
        result.put('Lead_History_Duration', settings.Lead_History_Duration__c);
        result.put('Lead_Statuses', settings.Lead_Status__c);
        result.put('Lead_Statuses_2', settings.Lead_Status_2__c);
        result.put('Lead_Matched_Reason', settings.Matched_Lead_Reason__c);
        result.put('Lead_Matched_Reason_Field', settings.Matched_Lead_Reason_Field__c);
        result.put('Lead_Matched_Status', settings.Matched_Lead_Status__c);

        // Opportunity custom setting values
        result.put('Opportunity_Address_PostalCode', settings.Opportunity_Address_PostalCode__c);
        result.put('Opportunity_Address_State', settings.Opportunity_Address_State__c);
        result.put('Opportunity_Address_Street', settings.Opportunity_Address_Street__c);
        result.put('Opportunity_Address_City', settings.Opportunity_Address_City__c);
        result.put('Opportunity_Record_Types', settings.Opportunity_Record_Types__c);
        result.put('Opportunity_History_Duration', settings.Opportunity_History_Duration__c);
        result.put('Opportunity_Stages', settings.Opportunity_Stage__c);
        result.put('Opportunity_Stages_2', settings.Opportunity_Stage_2__c);
        result.put('Opportunity_Matched_Reason', settings.Matched_Opportunity_Reason__c);
        result.put('Opportunity_Matched_Reason_Field', settings.Matched_Opportunity_Reason_Field__c);
        result.put('Opportunity_Matched_Stage', settings.Matched_Opportunity_Stage__c);

        // Property custom setting values
        result.put('Property_Sales_History_Duration', settings.Property_Sales_History_Duration__c);
        result.put('Matching_Day', settings.Matching_Day__c);
        result.put('AutomaticUpdate', settings.AutomaticUpdate__c);

        result.put('IsSetupComplete', settings.IsSetupComplete__c);
        return result;
    }

    @AuraEnabled
    public static void updateIsSetupComplete(){
        try {
            Property_SalesAI_Settings__c settings = Property_SalesAI_Settings__c.getOrgDefaults();
            settings.IsSetupComplete__c = true;
            if (Schema.sObjectType.Property_SalesAI_Settings__c.isUpdateable() && Schema.sObjectType.Property_SalesAI_Settings__c.isCreateable()) {
                upsert settings;
                String cronExp = getCronExpressionFromDay(settings.Matching_Day__c);
                System.schedule('Matching logic weekly run', cronExp, new LeadAndOppMatchingScheduler());
               	Lmg_AddressKeyIntegration_cls.scheduleNightlyBatch();
               	Lmg_SimilarityKeyHelper_cls.createCustomSettingDefault();

            } else {
                Exception ex = new AuraHandledException('No access to modify custom setting');
                ex.setMessage('No access to modify custom setting');
                throw ex;    
            }
        } catch (Exception e) {
            Exception ex = new AuraHandledException(e.getMessage());
            ex.setMessage(e.getMessage());
            throw ex;
        }
    }

    @AuraEnabled
    public static void saveCustomSetting(String objectApiName, Map<String, String> settingsMap) {
       
        // Retrieve the custom setting instance
        Property_SalesAI_Settings__c customSetting = Property_SalesAI_Settings__c.getOrgDefaults();
        Boolean reschedule = false;
        try {
            // Dynamically assign field values based on the object API name and the map provided
            for (String field : settingsMap.keySet()) {
                String fieldValue = settingsMap.get(field);
                if (field.contains('Duration')) {
                    // Convert string to integer for duration fields
                    Integer duration = Integer.valueOf(fieldValue);
                    putField(customSetting, field, duration);
                } else if (field.contains('Automatic')) {
                    // Convert string to boolean for Automatic fields
                    Boolean automatic = Boolean.valueOf(fieldValue);
                    putField(customSetting, field, automatic);
                } else {
                    // Directly assign string values for other fields
                    if (field.contains('Matching_Day') &&
                    customSetting.IsSetupComplete__c && customSetting.Matching_Day__c != null &&
                    !customSetting.Matching_Day__c.equals(fieldValue)) {
                        reschedule = true;
                    }
                    putField(customSetting, field, fieldValue);
                }
            }
            if (Schema.sObjectType.Property_SalesAI_Settings__c.isUpdateable() && Schema.sObjectType.Property_SalesAI_Settings__c.isCreateable()) {
                upsert customSetting;
            } else {
                throw new AuraHandledException('Insufficient permissions to update custom settings.');
            }
            if (reschedule) {
                // Query the existing scheduled job
                CronTrigger ct = [SELECT Id, CronJobDetail.Name 
                    FROM CronTrigger 
                    WHERE CronJobDetail.Name = 'Matching logic weekly run' 
                    WITH SECURITY_ENFORCED LIMIT 1];
                
                // Abort the existing job if found
                if (ct != null) {
                    System.abortJob(ct.Id);
                }
                
                // Schedule the new job
                String cronExp = getCronExpressionFromDay(customSetting.Matching_Day__c);
                System.schedule('Matching logic weekly run', cronExp, new LeadAndOppMatchingScheduler());
            }
        } catch (Exception e) {
            Exception ex = new AuraHandledException('Error saving custom settings: ' + e.getMessage());
            ex.setMessage('Error saving custom settings: ' + e.getMessage());
            throw ex;
        }
    }

    /**
     * Helper method to put values in SObject fields dynamically.
     */
    static void putField(SObject obj, String fieldName, Object value) {
        Schema.SObjectType objectType = obj.getSObjectType();
        Schema.DescribeSObjectResult objectDescribe = objectType.getDescribe();
        Map<String, Schema.SObjectField> fieldMap = objectDescribe.fields.getMap();
        String namespacePrefix = getNamespacePrefixForObject(objectDescribe); 
        String key = namespacePrefix + fieldName;

        if (fieldMap.containsKey(key)) {
            obj.put(key, value);
        } else if (fieldMap.containsKey(fieldName)) {
            obj.put(fieldName, value);
        } else {
            Exception ex = new AuraHandledException('Field does not exist: ' + fieldName);
            ex.setMessage('Field does not exist: ' + fieldName);
            throw ex;
        }
    }

    static String getNamespacePrefixForObject(Schema.DescribeSObjectResult objectDescribe){
        String fullName = objectDescribe.getName();       // E.g., 'lmgpilot__CustomSetting__c' or 'CustomSetting__c'
        String localName = objectDescribe.getLocalName(); // E.g., 'CustomSetting__c'
        // Determine the namespace prefix
        String namespacePrefix = '';
        if (!fullName.equals(localName)) {
            // Extract the namespace prefix by removing the local name from the full name
            namespacePrefix = fullName.substring(0, fullName.indexOf(localName));
        }    
        return namespacePrefix;
    }

    public static String getCronExpressionFromDay(String day) {
        String cronExp;
        if (day !=null) {
            cronExp = '0 0 0 ? * ';
            cronExp += day.substring(0,3).toUpperCase();
            return cronExp;
        }
        return cronExp;
    }

    public class PickListWrapper {
        @AuraEnabled
        public String label { get; set; }
        @AuraEnabled
        public String value {get; set; }

        PickListWrapper(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }
}