force-app/main/default/objects/Property_SalesAI_History__c/Property_SalesAI_History__c.object-meta.xml
<CustomObject>
    <label>Property Sales.AI History</label>
    <nameField>
        <label>Property Sales.AI History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties Sales.AI History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_SalesAI_History__c/fields/Finish_Time__c.field-meta.xml
<CustomField>
    <fullName>Finish_Time__c</fullName>
    <label>Finish Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_History__c/fields/Matched_Leads__c.field-meta.xml
<CustomField>
    <fullName>Matched_Leads__c</fullName>
    <label>Matched Leads</label>
    <summaryFilterItems>
        <field>Property_SalesAI_Match__c.Type__c</field>
        <operation>equals</operation>
        <value>Lead Match</value>
    </summaryFilterItems>
    <summaryForeignKey>Property_SalesAI_Match__c.Property_SalesAI_History__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_History__c/fields/Matched_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Matched_Opportunities__c</fullName>
    <label>Matched Opportunities</label>
    <summaryFilterItems>
        <field>Property_SalesAI_Match__c.Type__c</field>
        <operation>equals</operation>
        <value>Opportunity Match</value>
    </summaryFilterItems>
    <summaryForeignKey>Property_SalesAI_Match__c.Property_SalesAI_History__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Finished Successfully</fullName>
            </value>
            <value>
                <fullName>Finished With Errors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/Property_SalesAI_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Property Sales.AI Settings</label>
</CustomObject>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/IsSetupComplete__c.field-meta.xml
<CustomField>
    <fullName>IsSetupComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A boolean that is set to true only when the required fields above are populated by the UX</description>
    <label>IsSetupComplete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Lead_Address_City__c</fullName>
    <label>Lead Address City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_Address_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Lead_Address_PostalCode__c</fullName>
    <description>What field to use the postalcode to match against</description>
    <label>Lead Address PostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Lead_Address_State__c</fullName>
    <description>What field to use to retrieve the state to match against</description>
    <label>Lead Address State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_Address_Street__c.field-meta.xml
<CustomField>
    <fullName>Lead_Address_Street__c</fullName>
    <description>What field to use to retrieve the street address to match against</description>
    <label>Lead Address Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_History_Duration__c.field-meta.xml
<CustomField>
    <fullName>Lead_History_Duration__c</fullName>
    <description>To define the scope of Leads to query, this number is the # of days, in the past, we want to query the LastModifiedDate and/or CreatedDate</description>
    <label>Lead History Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Lead_Record_Types__c</fullName>
    <description>A comma separated list of 1 or more Lead Record Types</description>
    <label>Lead Record Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <description>To define the scope of Leads to query, this is the 1 or more lead status to include. A comma separated list of Lead.Status picklist values</description>
    <label>Lead Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Matched_Lead_Reason__c.field-meta.xml
<CustomField>
    <fullName>Matched_Lead_Reason__c</fullName>
    <description>When a Lead match is found, what &quot;lead reason&quot; to populate</description>
    <label>Matched Lead Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Matched_Lead_Reason_Field__c.field-meta.xml
<CustomField>
    <fullName>Matched_Lead_Reason_Field__c</fullName>
    <description>When a Lead match is found, what Lead field to also update the Reason</description>
    <label>Matched Lead Reason Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Matched_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Matched_Lead_Status__c</fullName>
    <description>When a Lead match is found, what is the lead.status to update</description>
    <label>Matched Lead Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Matched_Opportunity_Reason__c.field-meta.xml
<CustomField>
    <fullName>Matched_Opportunity_Reason__c</fullName>
    <description>When an Opportunity match is found, what is the lost reason to populate</description>
    <label>Matched Opportunity Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Matched_Opportunity_Reason_Field__c.field-meta.xml
<CustomField>
    <fullName>Matched_Opportunity_Reason_Field__c</fullName>
    <description>When an Opportunity match is found, what is the Opportunity field to update the lost reason</description>
    <label>Matched Opportunity Reason Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Matched_Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Matched_Opportunity_Stage__c</fullName>
    <description>When an Opportunity match is found, what is the opportunity.stagename value to update</description>
    <label>Matched Opportunity Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Matching_Day__c.field-meta.xml
<CustomField>
    <fullName>Matching_Day__c</fullName>
    <description>Day of the week that the matching logic will run</description>
    <label>Matching Day</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Address_City__c</fullName>
    <description>What field to use to retrieve the city to match against</description>
    <label>Opportunity Address City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_Address_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Address_PostalCode__c</fullName>
    <description>What field to use the postalcode to match against</description>
    <label>Opportunity Address PostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Address_State__c</fullName>
    <description>What field to use to retrieve the state to match against</description>
    <label>Opportunity Address State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_Address_Street__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Address_Street__c</fullName>
    <description>What field to use to retrieve the street address to match against</description>
    <label>Opportunity Address Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_History_Duration__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_History_Duration__c</fullName>
    <description>To define the scope of Opportunity to query, this number is the # of days, in the past, we want to query the LastModifiedDate and/or CreatedDate</description>
    <label>Opportunity History Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record_Types__c</fullName>
    <description>A comma separated list of 1 or more Opportunity Record Types</description>
    <label>Opportunity Record Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <description>To define the scope of Opportunities to query, this is the 1 or more Opportunity Stage(s) to include. A comma separated list of Opportunity.StageName picklist values</description>
    <label>Opportunity Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_SalesAI_Settings__c/fields/Property_Sales_History_Duration__c.field-meta.xml
<CustomField>
    <fullName>Property_Sales_History_Duration__c</fullName>
    <description>To define the scope of Property Sales.AI records to include in the matching logic, this number is the # of days in the past (based on the property sold date) we want to query.</description>
    <label>Property Sales History Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ConfigurationControllerTest.cls
@isTest
private class ConfigurationControllerTest {

    @testSetup
    static void setupTestData() {
        // Initialize custom settings with default values
        Property_SalesAI_Settings__c settings = new Property_SalesAI_Settings__c(
            Lead_Address_PostalCode__c = '12345',
            Lead_Address_State__c = 'CA',
            Lead_Address_Street__c = '123 Main St',
            Lead_Address_City__c = 'San Francisco',
            Lead_Record_Types__c = 'LeadRecordTypeId',
            Lead_History_Duration__c = 90,
            Lead_Status__c = 'Open',
            Matched_Lead_Reason__c = 'Duplicate',
            Matched_Lead_Reason_Field__c = 'Reason__c',
            Matched_Lead_Status__c = 'Closed',

            Opportunity_Address_PostalCode__c = '67890',
            Opportunity_Address_State__c = 'NY',
            Opportunity_Address_Street__c = '456 Broadway',
            Opportunity_Address_City__c = 'New York',
            Opportunity_Record_Types__c = 'OppRecordTypeId',
            Opportunity_History_Duration__c = 180,
            Opportunity_Stage__c = 'Prospecting',
            Matched_Opportunity_Reason__c = 'Existing Client',
            Matched_Opportunity_Reason_Field__c = 'Reason__c',
            Matched_Opportunity_Stage__c = 'Closed Won',

            Property_Sales_History_Duration__c = 365,
            Matching_Day__c = 'Monday', // Converted Date to String
            IsSetupComplete__c = false
        );
        insert settings;
        // Insert a sample Property_SalesAI_History__c record for testing
        Property_SalesAI_History__c historyRecord = new Property_SalesAI_History__c(
            Name = 'Test History',
            Finish_Time__c = DateTime.now().addDays(-1),
            Status__c = 'Completed'
        );
        insert historyRecord;
    }

    @isTest
    static void testGetRecordTypes() {
        // Query existing RecordTypes
        List<RecordType> leadRecordTypes = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Lead' LIMIT 1];
        List<RecordType> oppRecordTypes = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Opportunity' LIMIT 1];

        Test.startTest();
        List<RecordType> returnedLeadRecordTypes = ConfigurationController.getRecordTypes('Lead');
        List<RecordType> returnedOppRecordTypes = ConfigurationController.getRecordTypes('Opportunity');
        Test.stopTest();

        System.assertNotEquals(0, returnedLeadRecordTypes.size(), 'Lead record types should not be empty');
        System.assertNotEquals(0, returnedOppRecordTypes.size(), 'Opportunity record types should not be empty');
    }

    @isTest
    static void testGetStatuses() {
        Test.startTest();
        List<ConfigurationController.PickListWrapper> leadStatuses = ConfigurationController.getStatuses('Lead');
        List<ConfigurationController.PickListWrapper> oppStages = ConfigurationController.getStatuses('Opportunity');
        Test.stopTest();

        System.assertNotEquals(0, leadStatuses.size(), 'Lead statuses should not be empty');
        System.assertNotEquals(0, oppStages.size(), 'Opportunity stages should not be empty');
    }

    @isTest
    static void testGetCustomSettingValues() {
        Test.startTest();
        Map<String, Object> customSettings = ConfigurationController.getCustomSettingValues();
        Test.stopTest();

        System.assertEquals('12345', customSettings.get('Lead_Address_PostalCode'), 'Lead_Address_PostalCode should match');
        System.assertEquals('CA', customSettings.get('Lead_Address_State'), 'Lead_Address_State should match');
        System.assertEquals(false, customSettings.get('IsSetupComplete'), 'IsSetupComplete should be false initially');
    }

    @isTest
    static void testUpdateIsSetupComplete() {
        Property_SalesAI_Settings__c settingsBefore = [SELECT IsSetupComplete__c FROM Property_SalesAI_Settings__c LIMIT 1];
        System.assertEquals(false, settingsBefore.IsSetupComplete__c, 'IsSetupComplete should be false before update');
        List<CronTrigger> scheduledJobs = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = 'Matching logic weekly run'];
        if (!scheduledJobs.isEmpty()) {
            System.abortJob(scheduledJobs[0].Id);
        }
    
        Test.startTest();
        ConfigurationController.updateIsSetupComplete();
        Test.stopTest();

        Property_SalesAI_Settings__c settingsAfter = [SELECT IsSetupComplete__c FROM Property_SalesAI_Settings__c LIMIT 1];
        System.assertEquals(true, settingsAfter.IsSetupComplete__c, 'IsSetupComplete should be true after update');
    }

    @isTest
    static void testUpdateIsSetupCompleteJobScheduledTwice() {
        // Ensure IsSetupComplete is false before the test
        Property_SalesAI_Settings__c settingsBefore = [SELECT IsSetupComplete__c FROM Property_SalesAI_Settings__c LIMIT 1];
        System.assertEquals(false, settingsBefore.IsSetupComplete__c, 'IsSetupComplete should be false before update');
    
        // Abort any existing scheduled jobs named "Matching logic weekly run"
        List<CronTrigger> scheduledJobs = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = 'Matching logic weekly run'];
        for (CronTrigger ct : scheduledJobs) {
            System.abortJob(ct.Id);
        }
    
        Test.startTest();
        ConfigurationController.updateIsSetupComplete();    
        try {
            ConfigurationController.updateIsSetupComplete();
        } catch (Exception e) {
            System.debug('Exception message: ' + e.getMessage());
            System.assert(e.getMessage().contains('already scheduled'), 'Expected exception when scheduling job twice. Actual message: ' + e.getMessage());
        }
        Test.stopTest();
        Property_SalesAI_Settings__c settingsAfter = [SELECT IsSetupComplete__c FROM Property_SalesAI_Settings__c LIMIT 1];
        System.assertEquals(true, settingsAfter.IsSetupComplete__c, 'IsSetupComplete should be true after update');
        List<CronTrigger> jobsAfter = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = 'Matching logic weekly run'];
        System.assertEquals(1, jobsAfter.size(), 'Only one scheduled job should exist');
    }
    
    @isTest
    static void testGetCronExpressionFromDayNullDay() {
        // Delete the custom setting to simulate missing configuration
        delete [SELECT Id FROM Property_SalesAI_Settings__c LIMIT 1];

        Test.startTest();
        // Call the method with null input
        String cronExpression = ConfigurationController.getCronExpressionFromDay(null);
        Test.stopTest();

        // Assert that cronExpression is null
        System.assertEquals(null, cronExpression, 'Cron expression should be null when day is null');
    }


    @isTest
    static void testSaveCustomSettingValidData() {
        Map<String, String> settingsMap = new Map<String, String>{
            'Lead_Address_PostalCode__c' => '99999',
            'Lead_History_Duration__c'   => '45',
            'Lead_Status__c'             => 'New;Working',
            'Opportunity_Stage__c'       => 'Qualification',
            'Property_Sales_History_Duration__c' => '730'
        };

        Test.startTest();
        ConfigurationController.saveCustomSetting('Lead', settingsMap);
        Test.stopTest();

        Property_SalesAI_Settings__c updatedSettings = [SELECT Lead_Address_PostalCode__c, Lead_History_Duration__c, Lead_Status__c, Opportunity_Stage__c, Property_Sales_History_Duration__c FROM Property_SalesAI_Settings__c LIMIT 1];

        System.assertEquals('99999', updatedSettings.Lead_Address_PostalCode__c, 'Lead_Address_PostalCode should be updated');
        System.assertEquals(45, updatedSettings.Lead_History_Duration__c, 'Lead_History_Duration should be updated');
        System.assertEquals('New;Working', updatedSettings.Lead_Status__c, 'Lead_Status__c should be updated');
        System.assertEquals('Qualification', updatedSettings.Opportunity_Stage__c, 'Opportunity_Stage should be updated');
        System.assertEquals(730, updatedSettings.Property_Sales_History_Duration__c, 'Property_Sales_History_Duration should be updated');
    }

    @isTest
    static void testSaveCustomSettingInvalidField() {
        Map<String, String> settingsMap = new Map<String, String>{
            'Invalid_Field__c' => 'Some Value'
        };

        Test.startTest();
        try {
            ConfigurationController.saveCustomSetting('Lead', settingsMap);
            System.assert(false, 'Expected an exception due to invalid field');
        } catch (Exception e) {
            System.debug('Exception message: ' + e.getMessage());
            System.assert(e.getMessage().contains('Field does not exist'), 'Exception message should indicate missing field. Actual message: ' + e.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    static void testPutFieldMethod() {
        Map<String, String> settingsMap = new Map<String, String>{
            'Lead_Address_State__c' => 'TX'
        };

        Test.startTest();
        ConfigurationController.saveCustomSetting('Lead', settingsMap);
        Test.stopTest();

        Property_SalesAI_Settings__c updatedSettings = [SELECT Lead_Address_State__c FROM Property_SalesAI_Settings__c LIMIT 1];
        System.assertEquals('TX', updatedSettings.Lead_Address_State__c, 'Lead_Address_State should be updated to TX');
    }

    @isTest
    static void testSaveCustomSettingNonIntegerDuration() {
        Map<String, String> settingsMap = new Map<String, String>{
            'Lead_History_Duration__c' => 'NotANumber'
        };

        Test.startTest();
        try {
            ConfigurationController.saveCustomSetting('Lead', settingsMap);
            System.assert(false, 'Expected an exception due to invalid integer conversion');
        } catch (Exception e) {
            System.debug('Exception message: ' + e.getMessage());
            System.assert(e.getMessage().contains('Error saving custom settings'), 'Exception message should indicate error saving settings. Actual message: ' + e.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    static void testGetStatusesInvalidObject() {
        Test.startTest();
        List<ConfigurationController.PickListWrapper> statuses = ConfigurationController.getStatuses('InvalidObject');
        Test.stopTest();

        System.assertEquals(0, statuses.size(), 'Statuses list should be empty for invalid object');
    }

    @isTest
    static void testGetHistory() {
        // Call the Apex method
        Test.startTest();
        Map<String,Object> result = ConfigurationController.getExecutionHistory();
        Test.stopTest();

        // Validate the result is not null and contains the expected data
        System.assertNotEquals(null, result, 'Expected to retrieve a history record');
    //    System.assertEquals(0, result.get('Matched_Leads__c'), 'Expected 0 matched leads');
      //  System.assertEquals(0, result.get('Matched_Opportunities__c'), 'Expected 0 matched opportunities');
        System.assertEquals('Completed', result.get('Status__c'), 'Expected status to be Completed');
    }

    @isTest
    static void testGetPicklistValuesForField() {

        List<ConfigurationController.PickListWrapper> picklistValues = ConfigurationController.getPicklistValuesForField('Lead', 'Industry');

        // Assert: Verify that the picklist values are returned correctly
        System.assertNotEquals(null, picklistValues, 'Picklist values should not be null');
        System.assert(picklistValues.size() > 0, 'Picklist values should be retrieved');
    }

}